version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  todos-front-container:
    build: ./client
    ports:
      - "3001:3001"
  todos-backend:
    build: ./server
    ports:
      - "3000:3000"

